name: CI

on:
  push:
    branches: [main]

jobs:
  AWS:
    runs-on: ubuntu-latest
    steps:
      - name: GitHub Checkout
        uses: actions/checkout@v2

      - name: Setup
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install Yarn
        run: npm install -g yarn

      - name: Install NPM
        run: yarn

      - name: Build
        run: yarn build

      - name: Branch name
        run: echo running on branch ${{ github.ref }}

      - name: Deploy to AWS
        run: yarn deploy
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          STAGE: ${{ github.ref }}
